# NumPy Project 1

In [1]:
# NumPy is a Python library used for working with arrays. 
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [2]:
# Features OF NUMPY:
# It provides a high-performance multidimensional array object.
# It includes a large collection of mathematical functions that operate on arrays.
# It is integrated with a large number of scientific computing libraries.
# It is open source and freely available.


In [3]:
# There are 217 functionalities associated with NumPy.
# Will choose in a range of 5-10 based on their complexity and associativity to create projects.

### For Day 1 we will learn about importing NumPy and basic arithmatic functions

In [12]:
import numpy as np # NumPy comes pre-installed with anaconda
# if you haven't installed anaconda, I highly recommend to install it right away.

In [18]:
# Generating random data (this use case is most commonly used to generate OTP's)
data = np.random.randint(0, 100, size=(5, 5))
print("Random Data:")
print(data)

Random Data:
[[84 51 57  2 46]
 [22 71 19 22 91]
 [88 29 46  9 78]
 [32 11 18 41 13]
 [32 14 73  0 78]]


In [19]:
# Calculate sum of all elements
total_sum = np.sum(data)
print("Total Sum of All Elements:", total_sum)

Total Sum of All Elements: 1027


In [20]:
# Calculate mean of all elements
mean_value = np.mean(data)
print("Mean of All Elements:", mean_value)

Mean of All Elements: 41.08


In [21]:
# Find maximum value in the data
max_value = np.max(data)
print("Maximum Value in Data:", max_value)

Maximum Value in Data: 91


In [22]:
# Find minimum value in the data
min_value = np.min(data)
print("Minimum Value in Data:", min_value)

Minimum Value in Data: 0


In [23]:
# Calculate sum of each row
row_sums = np.sum(data, axis=1)
print("Sum of Each Row:")
print(row_sums)

Sum of Each Row:
[240 225 250 115 197]


In [24]:
# Calculate sum of each column
column_sums = np.sum(data, axis=0)
print("Sum of Each Column:")
print(column_sums)

Sum of Each Column:
[258 176 213  74 306]
